// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbl9eh8i7lpV0FQj8sLfgx-5XZjGXIxwQ',
    appId: '1:704922506956:web:bf497e103cbe2212461469',
    messagingSenderId: '704922506956',
    projectId: 'mess-app-e70c9',
    authDomain: 'mess-app-e70c9.firebaseapp.com',
    storageBucket: 'mess-app-e70c9.appspot.com',
    measurementId: 'G-L8Z9GSY7GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGaoKJPfVywGDRNpHDwA_uqKMyh-DyGk',
    appId: '1:704922506956:android:09c4f51975832e04461469',
    messagingSenderId: '704922506956',
    projectId: 'mess-app-e70c9',
    storageBucket: 'mess-app-e70c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA44rM2yDpH74gHyH5YTnVkMiXvcq9CH38',
    appId: '1:704922506956:ios:479c95cd1aa508ad461469',
    messagingSenderId: '704922506956',
    projectId: 'mess-app-e70c9',
    storageBucket: 'mess-app-e70c9.appspot.com',
    iosBundleId: 'com.example.messapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA44rM2yDpH74gHyH5YTnVkMiXvcq9CH38',
    appId: '1:704922506956:ios:25ab97c0e4267887461469',
    messagingSenderId: '704922506956',
    projectId: 'mess-app-e70c9',
    storageBucket: 'mess-app-e70c9.appspot.com',
    iosBundleId: 'com.example.messapp.RunnerTests',
  );
}
